name: E2E Test
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-record:
    runs-on: ubuntu-latest
    env:
      CI: true
      E2E_EDITOR_MODE: plain-text
      E2E_EVENTS_MODE: modern-events
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
      - run: npm i -g npm@8
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            packages/playwright-core/node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-CACHE_VERSION_SECRET-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Download browsers
        run: npx playwright install && npx @replayio/playwright install
      - run: npm run test-e2e-ci-replay
        env:
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.3
        with:
          public: true
          api-key: rwk_2MDN0nWD1k3EQR1XejqxtcyHNXrjYlc0lKo4Tz3RRhf
  playwright-no-record:
    runs-on: ubuntu-latest
    env:
      CI: true
      E2E_EDITOR_MODE: plain-text
      E2E_EVENTS_MODE: modern-events
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
      - run: npm i -g npm@8
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            packages/playwright-core/node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-CACHE_VERSION_SECRET-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Download browsers
        run: npx playwright install && npx @replayio/playwright install
      - run: npm run test-e2e-ci-replay
        env:
          RECORD_REPLAY_NO_RECORD: 1
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
  playwright-original:
    runs-on: ubuntu-latest
    env:
      CI: true
      E2E_EDITOR_MODE: plain-text
      E2E_EVENTS_MODE: modern-events
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
      - run: npm i -g npm@8
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            packages/playwright-core/node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-CACHE_VERSION_SECRET-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Download browsers
        run: npx playwright install
      - run: npm run test-e2e-ci-chromium
